spring:
  application:
    name: novisign
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: testpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect